name: Sync Submodules

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Push submodules
        run: |
          git submodule foreach --recursive 'git push'
